name: Azure CLI
on:
  push:
    branches:
      - 'main'
    paths:
      - 'trigger.md'
  workflow_dispatch:

jobs:
  Setup:
    name: Setup Ubuntu runner
    runs-on: ubuntu-latest
    steps:
#    - name: Azure login
#        uses: azure/login@v1
#        with:
#          creds: ${{ secrets.AZURE_CREDENTIALS }}
                            
      - name: Spin up CLI container
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az login
            az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
            az extension add --upgrade -s https://aka.ms/az-aroext-latest.whl
            az extension list
            az aro create cluster --help
