name: Setup ARO
on:
  push:
    branches:
      - 'main'
    paths:
      - 'trigger.md'
  workflow_dispatch:

jobs:
  Setup:
    name: Setup Ubuntu Runner
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Register Providers
      uses: azure/CLI@v1
      with:
        azcliversion: 2.6.0
        inlineScript: |
          az account show
          az --version
          az provider register -n Microsoft.RedHatOpenShift --wait
          az provider register -n Microsoft.Compute --wait
          az provider register -n Microsoft.Storage --wait
          az provider register -n Microsoft.Authorization --wait
          
