name: Setup ARO
on:
  push:
    branches:
      - 'main'
    paths:
      - 'trigger.md'
  workflow_dispatch:

jobs:
  Setup:
    name: Setup Ubuntu runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
          
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Register providers
        uses: azure/CLI@v1
        with:
          azcliversion: 2.6.0
          inlineScript: |
            az login
            az feature register --namespace Microsoft.RedHatOpenShift --name preview
