name: Setup ARO
on:
  push:
    branches:
      - 'main'
    paths:
      - 'trigger.md'
  workflow_dispatch:

jobs:
  Setup:
    name: Setup Ubuntu runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
          
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Register providers
        uses: azure/CLI@v1
        with:
          azcliversion: 2.6.0
          inlineScript: |
            
            az account show
            az --version
            az vm list-usage -l southcentralus --query "[?contains(name.value, 'standardDSv3Family')]" -o table
#            az provider register -n Microsoft.RedHatOpenShift --wait
#            az provider register -n Microsoft.Compute --wait
#            az provider register -n Microsoft.Storage --wait
#            az provider register -n Microsoft.Authorization --wait
          
