name: Setup ARO
on:
  push:
    branches:
      - 'main'
    paths:
      - 'trigger.md'
  workflow_dispatch:

jobs:
  Setup:
    name: Setup Ubuntu runner
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - uses: actions/checkout@main
      - name: Setup Working Directory for OCP Install
        run: |
          echo ${{ RED_HAT_PULLSECRET }} > $GITHUB_WORKSPACE/pull-secret.txt
        
      - name: Register providers
        uses: azure/CLI@v1
        with:
          azcliversion: 2.33.1
          inlineScript: |
            az account show
            cat $GITHUB_WORKSPACE/pull-secret.txt
